import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';

const sampleProducts = [
  {
    name: 'Classic Gold Solitaire Ring',
    sku: 'RING-GOLD-001',
    shortDescription: 'Elegant 22K gold solitaire ring with premium diamond',
    longDescription: '<p>This stunning solitaire ring features a brilliant-cut diamond set in 22K gold. Perfect for engagements and special occasions.</p>',
    category: 'Rings',
    subcategory: 'Solitaire',
    brand: 'LuxeLoom',
    tags: ['gold', 'diamond', 'solitaire', 'engagement'],
    regularPrice: 125000,
    sellingPrice: 115000,
    costPrice: 95000,
    taxRate: 3,
    stock: 10,
    lowStockThreshold: 3,
    allowBackorders: false,
    barcode: 'RING001',
    weight: 5.2,
    dimensions: 'Ring Size 6',
    shippingClass: 'Standard',
    processingTime: '3-5 days',
    product_type: 'Gold',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 3.5,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    diamondCarat: 0.5,
    diamondRatePerCarat: 120000,
    numberOfStones: 1,
    diamondCut: 'Excellent',
    diamondShape: 'Round',
    stoneClarity: 'VS1',
    stoneColor: 'G',
    jewelryType: 'Ring',
    jewelrySubType: 'Solitaire Ring',
    ringSetting: 'Prong',
    ringSize: '6',
    ringSizeSystem: 'US',
    ringWidth: 2.5,
    ringStyle: 'Classic',
    designStyle: 'Traditional',
    finishType: 'Polished',
    stoneSetting: 'Prong',
    stoneArrangement: 'Single',
    makingCharges: 15,
    makingChargesType: 'percentage',
    certification: 'GIA',
    certificationNumber: 'GIA123456',
    gender: 'Women',
    totalWeight: 4.0,
    hallmarked: true,
    bis_hallmark: true,
    hallmarkNumber: 'BIS2024001',
    customizable: true,
    engraving_available: true,
    engravingOptions: 'Name, Date, Initials',
    resizing_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    ],
    metaTitle: 'Classic Gold Solitaire Ring - 22K Gold with Diamond',
    metaDescription: 'Beautiful 22K gold solitaire ring with premium diamond. Perfect for engagements.',
    urlSlug: 'classic-gold-solitaire-ring',
    focusKeyword: 'gold solitaire ring',
    status: 'active',
    featured: true,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Diamond Tennis Bracelet',
    sku: 'BRACE-DIAMOND-001',
    shortDescription: 'Elegant diamond tennis bracelet in 18K gold',
    longDescription: '<p>Stunning tennis bracelet featuring multiple diamonds set in 18K gold. A timeless piece for any occasion.</p>',
    category: 'Bracelets',
    subcategory: 'Tennis',
    brand: 'LuxeLoom',
    tags: ['diamond', 'bracelet', 'tennis', 'gold'],
    regularPrice: 250000,
    sellingPrice: 225000,
    costPrice: 190000,
    taxRate: 3,
    stock: 8,
    lowStockThreshold: 2,
    allowBackorders: false,
    barcode: 'BRACE001',
    weight: 12.5,
    dimensions: '7 inches',
    shippingClass: 'Standard',
    processingTime: '3-5 days',
    product_type: 'Diamond',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 8.0,
    goldPurity: '18K',
    goldRatePerGram: 4500,
    diamondCarat: 3.0,
    diamondRatePerCarat: 80000,
    numberOfStones: 25,
    diamondCut: 'Very Good',
    diamondShape: 'Round',
    stoneClarity: 'VS2',
    stoneColor: 'H',
    jewelryType: 'Bracelet',
    jewelrySubType: 'Tennis Bracelet',
    braceletType: 'Tennis',
    braceletLength: 7,
    braceletLengthUnit: 'inches',
    braceletWidth: 3,
    designStyle: 'Modern',
    finishType: 'Polished',
    stoneSetting: 'Pave',
    stoneArrangement: 'Eternity',
    makingCharges: 18,
    makingChargesType: 'percentage',
    certification: 'IGI',
    gender: 'Women',
    totalWeight: 11.0,
    hallmarked: true,
    bis_hallmark: true,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1611591437281-8bfb43f6e7e6?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1611591437281-8bfb43f6e7e6?w=800',
    ],
    metaTitle: 'Diamond Tennis Bracelet - 18K Gold',
    metaDescription: 'Elegant diamond tennis bracelet in 18K gold. Perfect for special occasions.',
    urlSlug: 'diamond-tennis-bracelet',
    focusKeyword: 'diamond tennis bracelet',
    status: 'active',
    featured: true,
    trending: true,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Silver Chain Necklace',
    sku: 'NECK-SILVER-001',
    shortDescription: 'Classic silver chain necklace with elegant design',
    longDescription: '<p>Beautiful 925 silver chain necklace. Perfect for daily wear or special occasions.</p>',
    category: 'Necklaces',
    subcategory: 'Chain',
    brand: 'LuxeLoom',
    tags: ['silver', 'necklace', 'chain'],
    regularPrice: 8500,
    sellingPrice: 7500,
    costPrice: 6000,
    taxRate: 3,
    stock: 15,
    lowStockThreshold: 5,
    allowBackorders: false,
    barcode: 'NECK001',
    weight: 8.0,
    dimensions: '18 inches',
    shippingClass: 'Standard',
    processingTime: '2-3 days',
    product_type: 'Silver',
    hasSilver: true,
    silverWeight: 7.5,
    silverPurity: '925 Silver',
    silverRatePerGram: 75,
    jewelryType: 'Necklace',
    jewelrySubType: 'Chain Necklace',
    chainType: 'Rope',
    chainLength: 18,
    chainLengthUnit: 'inches',
    designStyle: 'Classic',
    finishType: 'Polished',
    makingCharges: 12,
    makingChargesType: 'percentage',
    occasion: 'Daily Wear',
    gender: 'Unisex',
    totalWeight: 7.5,
    hallmarked: true,
    bis_hallmark: false,
    customizable: true,
    engraving_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    ],
    metaTitle: 'Silver Chain Necklace - 925 Silver',
    metaDescription: 'Classic 925 silver chain necklace. Elegant and timeless.',
    urlSlug: 'silver-chain-necklace',
    focusKeyword: 'silver chain necklace',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gold Mangalsutra Set',
    sku: 'MANG-GOLD-001',
    shortDescription: 'Traditional 22K gold mangalsutra with matching chain',
    longDescription: '<p>Authentic traditional mangalsutra set in 22K gold. Perfect for weddings and special occasions.</p>',
    category: 'Mangalsutra',
    subcategory: 'Traditional',
    brand: 'LuxeLoom',
    tags: ['gold', 'mangalsutra', 'traditional', 'wedding'],
    regularPrice: 95000,
    sellingPrice: 85000,
    costPrice: 70000,
    taxRate: 3,
    stock: 12,
    lowStockThreshold: 3,
    allowBackorders: false,
    barcode: 'MANG001',
    weight: 15.0,
    dimensions: '20 inches',
    shippingClass: 'Standard',
    processingTime: '5-7 days',
    product_type: 'Gold',
    hasGold: true,
    goldWeight: 12.0,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    jewelryType: 'Mangalsutra',
    jewelrySubType: 'Traditional Mangalsutra',
    chainType: 'Rope',
    chainLength: 20,
    chainLengthUnit: 'inches',
    designStyle: 'Traditional',
    finishType: 'Polished',
    makingCharges: 20,
    makingChargesType: 'percentage',
    occasion: 'Wedding',
    gender: 'Women',
    totalWeight: 12.0,
    hallmarked: true,
    bis_hallmark: true,
    hallmarkNumber: 'BIS2024002',
    customizable: true,
    engraving_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    ],
    metaTitle: 'Gold Mangalsutra Set - 22K Gold Traditional',
    metaDescription: 'Traditional 22K gold mangalsutra set. Perfect for weddings.',
    urlSlug: 'gold-mangalsutra-set',
    focusKeyword: 'gold mangalsutra',
    status: 'active',
    featured: true,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Diamond Stud Earrings',
    sku: 'EARR-DIAMOND-001',
    shortDescription: 'Classic diamond stud earrings in 18K gold',
    longDescription: '<p>Timeless diamond stud earrings set in 18K gold. Perfect for everyday elegance.</p>',
    category: 'Earrings',
    subcategory: 'Stud',
    brand: 'LuxeLoom',
    tags: ['diamond', 'earrings', 'stud', 'gold'],
    regularPrice: 45000,
    sellingPrice: 40000,
    costPrice: 32000,
    taxRate: 3,
    stock: 20,
    lowStockThreshold: 5,
    allowBackorders: false,
    barcode: 'EARR001',
    weight: 2.5,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '2-3 days',
    product_type: 'Diamond',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 1.5,
    goldPurity: '18K',
    goldRatePerGram: 4500,
    diamondCarat: 0.5,
    diamondRatePerCarat: 100000,
    numberOfStones: 2,
    diamondCut: 'Excellent',
    diamondShape: 'Round',
    stoneClarity: 'VVS1',
    stoneColor: 'F',
    jewelryType: 'Earrings',
    jewelrySubType: 'Diamond Stud Earrings',
    earringType: 'Stud',
    earringBackType: 'Push Back',
    designStyle: 'Classic',
    finishType: 'Polished',
    stoneSetting: 'Prong',
    stoneArrangement: 'Single',
    makingCharges: 15,
    makingChargesType: 'percentage',
    certification: 'GIA',
    occasion: 'Daily Wear',
    gender: 'Women',
    totalWeight: 2.0,
    hallmarked: true,
    bis_hallmark: false,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    ],
    metaTitle: 'Diamond Stud Earrings - 18K Gold',
    metaDescription: 'Classic diamond stud earrings in 18K gold. Perfect for everyday wear.',
    urlSlug: 'diamond-stud-earrings',
    focusKeyword: 'diamond stud earrings',
    status: 'active',
    featured: false,
    trending: true,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gold Bangle Set',
    sku: 'BANG-GOLD-001',
    shortDescription: 'Traditional 22K gold bangle set with intricate designs',
    longDescription: '<p>Beautiful set of 22K gold bangles with traditional designs. Perfect for festivals and weddings.</p>',
    category: 'Bangles',
    subcategory: 'Traditional',
    brand: 'LuxeLoom',
    tags: ['gold', 'bangle', 'traditional', 'festival'],
    regularPrice: 75000,
    sellingPrice: 68000,
    costPrice: 55000,
    taxRate: 3,
    stock: 10,
    lowStockThreshold: 3,
    allowBackorders: false,
    barcode: 'BANG001',
    weight: 25.0,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '4-6 days',
    product_type: 'Gold',
    hasGold: true,
    goldWeight: 20.0,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    jewelryType: 'Bangle',
    jewelrySubType: 'Traditional Bangle Set',
    designStyle: 'Traditional',
    finishType: 'Polished',
    makingCharges: 18,
    makingChargesType: 'percentage',
    occasion: 'Festival',
    gender: 'Women',
    totalWeight: 20.0,
    hallmarked: true,
    bis_hallmark: true,
    hallmarkNumber: 'BIS2024003',
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
    ],
    metaTitle: 'Gold Bangle Set - 22K Gold Traditional',
    metaDescription: 'Traditional 22K gold bangle set with intricate designs.',
    urlSlug: 'gold-bangle-set',
    focusKeyword: 'gold bangle set',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Platinum Wedding Ring',
    sku: 'RING-PLAT-001',
    shortDescription: 'Elegant platinum wedding ring with diamond accents',
    longDescription: '<p>Sophisticated platinum wedding ring with diamond accents. A symbol of eternal love.</p>',
    category: 'Rings',
    subcategory: 'Wedding',
    brand: 'LuxeLoom',
    tags: ['platinum', 'ring', 'wedding', 'diamond'],
    regularPrice: 180000,
    sellingPrice: 165000,
    costPrice: 140000,
    taxRate: 3,
    stock: 8,
    lowStockThreshold: 2,
    allowBackorders: false,
    barcode: 'RING002',
    weight: 4.5,
    dimensions: 'Ring Size 7',
    shippingClass: 'Standard',
    processingTime: '5-7 days',
    product_type: 'Platinum',
    hasDiamond: true,
    diamondCarat: 0.3,
    diamondRatePerCarat: 150000,
    numberOfStones: 5,
    diamondCut: 'Very Good',
    diamondShape: 'Round',
    stoneClarity: 'VS1',
    stoneColor: 'G',
    jewelryType: 'Ring',
    jewelrySubType: 'Wedding Ring',
    ringSetting: 'Channel',
    ringSize: '7',
    ringSizeSystem: 'US',
    ringWidth: 3.0,
    ringStyle: 'Modern',
    designStyle: 'Contemporary',
    finishType: 'Polished',
    stoneSetting: 'Channel',
    stoneArrangement: 'Eternity',
    makingCharges: 20,
    makingChargesType: 'percentage',
    certification: 'IGI',
    occasion: 'Wedding',
    gender: 'Unisex',
    totalWeight: 4.2,
    hallmarked: true,
    bis_hallmark: false,
    customizable: true,
    engraving_available: true,
    engravingOptions: 'Names, Date',
    resizing_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    ],
    metaTitle: 'Platinum Wedding Ring - Diamond Accents',
    metaDescription: 'Elegant platinum wedding ring with diamond accents. Perfect for weddings.',
    urlSlug: 'platinum-wedding-ring',
    focusKeyword: 'platinum wedding ring',
    status: 'active',
    featured: true,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Silver Pendant Set',
    sku: 'PEND-SILVER-001',
    shortDescription: 'Beautiful silver pendant set with chain',
    longDescription: '<p>Elegant 925 silver pendant set with matching chain. Perfect for gifting.</p>',
    category: 'Pendants',
    subcategory: 'Silver',
    brand: 'LuxeLoom',
    tags: ['silver', 'pendant', 'chain'],
    regularPrice: 12000,
    sellingPrice: 10500,
    costPrice: 8500,
    taxRate: 3,
    stock: 18,
    lowStockThreshold: 5,
    allowBackorders: false,
    barcode: 'PEND001',
    weight: 6.0,
    dimensions: '18 inches',
    shippingClass: 'Standard',
    processingTime: '2-3 days',
    product_type: 'Silver',
    hasSilver: true,
    silverWeight: 5.5,
    silverPurity: '925 Silver',
    silverRatePerGram: 75,
    jewelryType: 'Pendant',
    jewelrySubType: 'Silver Pendant',
    chainType: 'Box',
    chainLength: 18,
    chainLengthUnit: 'inches',
    designStyle: 'Modern',
    finishType: 'Polished',
    makingCharges: 10,
    makingChargesType: 'percentage',
    occasion: 'Daily Wear',
    gender: 'Women',
    totalWeight: 5.5,
    hallmarked: true,
    bis_hallmark: false,
    customizable: true,
    engraving_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    ],
    metaTitle: 'Silver Pendant Set - 925 Silver',
    metaDescription: 'Beautiful 925 silver pendant set with chain.',
    urlSlug: 'silver-pendant-set',
    focusKeyword: 'silver pendant',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gold and Diamond Necklace',
    sku: 'NECK-GOLD-DIAMOND-001',
    shortDescription: 'Luxurious gold necklace with diamond centerpiece',
    longDescription: '<p>Exquisite 22K gold necklace featuring a stunning diamond centerpiece. Perfect for special occasions.</p>',
    category: 'Necklaces',
    subcategory: 'Diamond',
    brand: 'LuxeLoom',
    tags: ['gold', 'diamond', 'necklace', 'luxury'],
    regularPrice: 350000,
    sellingPrice: 320000,
    costPrice: 270000,
    taxRate: 3,
    stock: 5,
    lowStockThreshold: 1,
    allowBackorders: false,
    barcode: 'NECK002',
    weight: 18.0,
    dimensions: '20 inches',
    shippingClass: 'Premium',
    processingTime: '7-10 days',
    product_type: 'Diamond',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 15.0,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    diamondCarat: 2.5,
    diamondRatePerCarat: 120000,
    numberOfStones: 1,
    diamondCut: 'Excellent',
    diamondShape: 'Round',
    stoneClarity: 'VVS1',
    stoneColor: 'D',
    jewelryType: 'Necklace',
    jewelrySubType: 'Diamond Necklace',
    chainType: 'Rope',
    chainLength: 20,
    chainLengthUnit: 'inches',
    designStyle: 'Ornate',
    finishType: 'Polished',
    stoneSetting: 'Prong',
    stoneArrangement: 'Single',
    makingCharges: 25,
    makingChargesType: 'percentage',
    certification: 'GIA',
    certificationNumber: 'GIA789012',
    occasion: 'Wedding',
    gender: 'Women',
    totalWeight: 17.5,
    hallmarked: true,
    bis_hallmark: true,
    hallmarkNumber: 'BIS2024004',
    customizable: true,
    engraving_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1611591437281-8bfb43f6e7e6?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1611591437281-8bfb43f6e7e6?w=800',
    ],
    metaTitle: 'Gold and Diamond Necklace - 22K Gold Luxury',
    metaDescription: 'Luxurious 22K gold necklace with diamond centerpiece.',
    urlSlug: 'gold-diamond-necklace',
    focusKeyword: 'gold diamond necklace',
    status: 'active',
    featured: true,
    trending: true,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Silver Nose Pin',
    sku: 'NOSE-SILVER-001',
    shortDescription: 'Traditional silver nose pin with elegant design',
    longDescription: '<p>Beautiful 925 silver nose pin with traditional design. Perfect for daily wear.</p>',
    category: 'Nose Pin',
    subcategory: 'Traditional',
    brand: 'LuxeLoom',
    tags: ['silver', 'nose pin', 'traditional'],
    regularPrice: 2500,
    sellingPrice: 2200,
    costPrice: 1800,
    taxRate: 3,
    stock: 25,
    lowStockThreshold: 8,
    allowBackorders: false,
    barcode: 'NOSE001',
    weight: 1.5,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '1-2 days',
    product_type: 'Silver',
    hasSilver: true,
    silverWeight: 1.2,
    silverPurity: '925 Silver',
    silverRatePerGram: 75,
    jewelryType: 'Nose Pin',
    jewelrySubType: 'Traditional Nose Pin',
    designStyle: 'Traditional',
    finishType: 'Polished',
    makingCharges: 8,
    makingChargesType: 'percentage',
    occasion: 'Daily Wear',
    gender: 'Women',
    totalWeight: 1.2,
    hallmarked: true,
    bis_hallmark: false,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    ],
    metaTitle: 'Silver Nose Pin - 925 Silver Traditional',
    metaDescription: 'Traditional 925 silver nose pin with elegant design.',
    urlSlug: 'silver-nose-pin',
    focusKeyword: 'silver nose pin',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gold Toe Ring Set',
    sku: 'TOE-GOLD-001',
    shortDescription: 'Traditional 22K gold toe ring set',
    longDescription: '<p>Beautiful set of 22K gold toe rings. Traditional design perfect for festivals.</p>',
    category: 'Toe Ring',
    subcategory: 'Traditional',
    brand: 'LuxeLoom',
    tags: ['gold', 'toe ring', 'traditional'],
    regularPrice: 8500,
    sellingPrice: 7500,
    costPrice: 6000,
    taxRate: 3,
    stock: 20,
    lowStockThreshold: 6,
    allowBackorders: false,
    barcode: 'TOE001',
    weight: 2.0,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '2-3 days',
    product_type: 'Gold',
    hasGold: true,
    goldWeight: 1.5,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    jewelryType: 'Toe Ring',
    jewelrySubType: 'Traditional Toe Ring',
    designStyle: 'Traditional',
    finishType: 'Polished',
    makingCharges: 12,
    makingChargesType: 'percentage',
    occasion: 'Festival',
    gender: 'Women',
    totalWeight: 1.5,
    hallmarked: true,
    bis_hallmark: true,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
    ],
    metaTitle: 'Gold Toe Ring Set - 22K Gold',
    metaDescription: 'Traditional 22K gold toe ring set.',
    urlSlug: 'gold-toe-ring-set',
    focusKeyword: 'gold toe ring',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Diamond Halo Ring',
    sku: 'RING-HALO-001',
    shortDescription: 'Stunning diamond halo ring in 18K gold',
    longDescription: '<p>Beautiful halo ring featuring a center diamond surrounded by smaller diamonds in 18K gold.</p>',
    category: 'Rings',
    subcategory: 'Halo',
    brand: 'LuxeLoom',
    tags: ['diamond', 'ring', 'halo', 'gold'],
    regularPrice: 95000,
    sellingPrice: 85000,
    costPrice: 70000,
    taxRate: 3,
    stock: 12,
    lowStockThreshold: 3,
    allowBackorders: false,
    barcode: 'RING003',
    weight: 3.8,
    dimensions: 'Ring Size 6',
    shippingClass: 'Standard',
    processingTime: '4-6 days',
    product_type: 'Diamond',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 2.5,
    goldPurity: '18K',
    goldRatePerGram: 4500,
    diamondCarat: 1.0,
    diamondRatePerCarat: 110000,
    numberOfStones: 15,
    diamondCut: 'Very Good',
    diamondShape: 'Round',
    stoneClarity: 'VS1',
    stoneColor: 'G',
    jewelryType: 'Ring',
    jewelrySubType: 'Halo Ring',
    ringSetting: 'Halo',
    ringSize: '6',
    ringSizeSystem: 'US',
    ringWidth: 2.0,
    ringStyle: 'Modern',
    designStyle: 'Contemporary',
    finishType: 'Polished',
    stoneSetting: 'Prong',
    stoneArrangement: 'Halo',
    makingCharges: 18,
    makingChargesType: 'percentage',
    certification: 'IGI',
    gender: 'Women',
    totalWeight: 3.5,
    hallmarked: true,
    bis_hallmark: false,
    customizable: true,
    engraving_available: true,
    resizing_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    ],
    metaTitle: 'Diamond Halo Ring - 18K Gold',
    metaDescription: 'Stunning diamond halo ring in 18K gold.',
    urlSlug: 'diamond-halo-ring',
    focusKeyword: 'diamond halo ring',
    status: 'active',
    featured: false,
    trending: true,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Silver Anklet Set',
    sku: 'ANK-SILVER-001',
    shortDescription: 'Elegant silver anklet set with traditional design',
    longDescription: '<p>Beautiful 925 silver anklet set. Perfect for traditional occasions.</p>',
    category: 'Anklet',
    subcategory: 'Traditional',
    brand: 'LuxeLoom',
    tags: ['silver', 'anklet', 'traditional'],
    regularPrice: 4500,
    sellingPrice: 4000,
    costPrice: 3200,
    taxRate: 3,
    stock: 22,
    lowStockThreshold: 7,
    allowBackorders: false,
    barcode: 'ANK001',
    weight: 3.5,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '2-3 days',
    product_type: 'Silver',
    hasSilver: true,
    silverWeight: 3.0,
    silverPurity: '925 Silver',
    silverRatePerGram: 75,
    jewelryType: 'Anklet',
    jewelrySubType: 'Traditional Anklet',
    designStyle: 'Traditional',
    finishType: 'Polished',
    makingCharges: 10,
    makingChargesType: 'percentage',
    occasion: 'Festival',
    gender: 'Women',
    totalWeight: 3.0,
    hallmarked: true,
    bis_hallmark: false,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    ],
    metaTitle: 'Silver Anklet Set - 925 Silver',
    metaDescription: 'Elegant 925 silver anklet set with traditional design.',
    urlSlug: 'silver-anklet-set',
    focusKeyword: 'silver anklet',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gold Chain for Men',
    sku: 'CHAIN-GOLD-MEN-001',
    shortDescription: 'Heavy 22K gold chain for men',
    longDescription: '<p>Sturdy 22K gold chain designed for men. Perfect for daily wear or special occasions.</p>',
    category: 'Chains',
    subcategory: 'Men',
    brand: 'LuxeLoom',
    tags: ['gold', 'chain', 'men'],
    regularPrice: 125000,
    sellingPrice: 115000,
    costPrice: 95000,
    taxRate: 3,
    stock: 8,
    lowStockThreshold: 2,
    allowBackorders: false,
    barcode: 'CHAIN001',
    weight: 22.0,
    dimensions: '22 inches',
    shippingClass: 'Standard',
    processingTime: '5-7 days',
    product_type: 'Gold',
    hasGold: true,
    goldWeight: 20.0,
    goldPurity: '22K',
    goldRatePerGram: 5500,
    jewelryType: 'Chain',
    jewelrySubType: 'Men Chain',
    chainType: 'Curb',
    chainLength: 22,
    chainLengthUnit: 'inches',
    designStyle: 'Modern',
    finishType: 'Polished',
    makingCharges: 15,
    makingChargesType: 'percentage',
    occasion: 'Daily Wear',
    gender: 'Men',
    totalWeight: 20.0,
    hallmarked: true,
    bis_hallmark: true,
    hallmarkNumber: 'BIS2024005',
    customizable: true,
    engraving_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
    ],
    metaTitle: 'Gold Chain for Men - 22K Gold',
    metaDescription: 'Heavy 22K gold chain designed for men.',
    urlSlug: 'gold-chain-men',
    focusKeyword: 'gold chain men',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Diamond Three Stone Ring',
    sku: 'RING-THREE-001',
    shortDescription: 'Elegant three stone diamond ring in 18K gold',
    longDescription: '<p>Beautiful three stone ring symbolizing past, present, and future. Set in 18K gold.</p>',
    category: 'Rings',
    subcategory: 'Three Stone',
    brand: 'LuxeLoom',
    tags: ['diamond', 'ring', 'three stone', 'gold'],
    regularPrice: 180000,
    sellingPrice: 165000,
    costPrice: 140000,
    taxRate: 3,
    stock: 6,
    lowStockThreshold: 1,
    allowBackorders: false,
    barcode: 'RING004',
    weight: 4.5,
    dimensions: 'Ring Size 7',
    shippingClass: 'Premium',
    processingTime: '7-10 days',
    product_type: 'Diamond',
    hasGold: true,
    hasDiamond: true,
    goldWeight: 3.0,
    goldPurity: '18K',
    goldRatePerGram: 4500,
    diamondCarat: 1.5,
    diamondRatePerCarat: 130000,
    numberOfStones: 3,
    diamondCut: 'Excellent',
    diamondShape: 'Round',
    stoneClarity: 'VVS2',
    stoneColor: 'F',
    jewelryType: 'Ring',
    jewelrySubType: 'Three Stone Ring',
    ringSetting: 'Three Stone',
    ringSize: '7',
    ringSizeSystem: 'US',
    ringWidth: 2.5,
    ringStyle: 'Classic',
    designStyle: 'Traditional',
    finishType: 'Polished',
    stoneSetting: 'Prong',
    stoneArrangement: 'Three Stone',
    makingCharges: 20,
    makingChargesType: 'percentage',
    certification: 'GIA',
    certificationNumber: 'GIA345678',
    occasion: 'Anniversary',
    gender: 'Women',
    totalWeight: 4.5,
    hallmarked: true,
    bis_hallmark: false,
    customizable: true,
    engraving_available: true,
    resizing_available: true,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
    ],
    metaTitle: 'Diamond Three Stone Ring - 18K Gold',
    metaDescription: 'Elegant three stone diamond ring in 18K gold.',
    urlSlug: 'diamond-three-stone-ring',
    focusKeyword: 'three stone ring',
    status: 'active',
    featured: true,
    trending: false,
    allowReviews: true,
    free_shipping: true,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Silver Hoop Earrings',
    sku: 'EARR-SILVER-HOOP-001',
    shortDescription: 'Classic silver hoop earrings',
    longDescription: '<p>Timeless 925 silver hoop earrings. Perfect for everyday elegance.</p>',
    category: 'Earrings',
    subcategory: 'Hoops',
    brand: 'LuxeLoom',
    tags: ['silver', 'earrings', 'hoops'],
    regularPrice: 3500,
    sellingPrice: 3000,
    costPrice: 2400,
    taxRate: 3,
    stock: 30,
    lowStockThreshold: 10,
    allowBackorders: false,
    barcode: 'EARR002',
    weight: 2.0,
    dimensions: 'Standard',
    shippingClass: 'Standard',
    processingTime: '1-2 days',
    product_type: 'Silver',
    hasSilver: true,
    silverWeight: 1.8,
    silverPurity: '925 Silver',
    silverRatePerGram: 75,
    jewelryType: 'Earrings',
    jewelrySubType: 'Hoop Earrings',
    earringType: 'Hoops',
    earringBackType: 'Hinged',
    designStyle: 'Classic',
    finishType: 'Polished',
    makingCharges: 8,
    makingChargesType: 'percentage',
    occasion: 'Daily Wear',
    gender: 'Women',
    totalWeight: 1.8,
    hallmarked: true,
    bis_hallmark: false,
    customizable: false,
    engraving_available: false,
    gift_wrapping: true,
    livePriceEnabled: true,
    mainImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
    ],
    metaTitle: 'Silver Hoop Earrings - 925 Silver',
    metaDescription: 'Classic 925 silver hoop earrings.',
    urlSlug: 'silver-hoop-earrings',
    focusKeyword: 'silver hoop earrings',
    status: 'active',
    featured: false,
    trending: false,
    allowReviews: true,
    free_shipping: false,
    allow_return: true,
    return_policy: '30 days return policy',
    vendor: '',
    variants: [],
    relatedProducts: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export async function POST(request: NextRequest) {
  try {
    const { db } = await connectToDatabase();
    
    // Check for force parameter
    const { searchParams } = new URL(request.url);
    const force = searchParams.get('force') === 'true';
    
    // Check if products already exist
    const existingCount = await db.collection('products').countDocuments();
    if (existingCount > 0 && !force) {
      return NextResponse.json(
        { 
          message: `Database already contains ${existingCount} products. To add sample products, please delete existing products first or use force=true parameter.`,
          existingCount,
          hint: 'Add ?force=true to the URL to add products anyway'
        },
        { status: 400 }
      );
    }
    
    // If force is true, we'll add products anyway (they might have different SKUs)
    // Insert sample products
    const result = await db.collection('products').insertMany(sampleProducts);
    
    return NextResponse.json({
      success: true,
      message: `Successfully added ${result.insertedCount} sample products!`,
      insertedCount: result.insertedCount,
      products: sampleProducts.map(p => ({
        name: p.name,
        sku: p.sku,
        price: p.sellingPrice,
      })),
    });
  } catch (error) {
    console.error('Error adding sample products:', error);
    return NextResponse.json(
      { error: 'Failed to add sample products', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}


