export const MOCK_VENDORS = [
  {
    id: '1',
    _id: '1',
    storeName: 'TechGear Store',
    storeSlug: 'techgear-store',
    name: 'TechGear Co',
    ownerName: 'Rajesh Kumar',
    email: 'vendor@techgear.com',
    phone: '+91-9876543210',
    alternatePhone: '+91-9876543211',
    whatsappNumber: '+91-9876543210',
    businessType: 'company' as const,
    gstNumber: '27AAPCT1234H1Z0',
    panNumber: 'AAACT1234H',
    businessRegistrationNumber: 'BRN-2024-001',
    description: 'Premium tech accessories and gadgets for all your electronic needs.',
    address1: '123 Tech Park',
    address2: 'Ground Floor',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560001',
    country: 'India',
    bankName: 'HDFC Bank',
    accountHolderName: 'TechGear Co Pvt Ltd',
    accountNumber: '1234567890123456',
    ifscCode: 'HDFC0001234',
    upiId: 'techgear@hdfc',
    logo: 'https://via.placeholder.com/200x200?text=TechGear',
    banner: 'https://via.placeholder.com/1920x400?text=TechGear+Banner',
    commissionRate: 5.5,
    allowedCategories: ['1', '2'],
    products: 24,
    facebook: 'https://facebook.com/techgear',
    instagram: 'https://instagram.com/techgear',
    twitter: 'https://twitter.com/techgear',
    website: 'https://techgear.com',
    idProof: 'https://example.com/id-proof-1.pdf',
    addressProof: 'https://example.com/address-proof-1.pdf',
    gstCertificate: 'https://example.com/gst-cert-1.pdf',
    cancelledCheque: 'https://example.com/cheque-1.pdf',
    status: 'approved' as const,
    approvalNotes: 'All documents verified. Approved for listing.',
    emailVerified: true,
    phoneVerified: true,
    documentsVerified: true,
    username: 'techgear_store',
    password: 'hashed_password_here',
    sendCredentialsEmail: false,
    registrationDate: '2024-01-15',
  },
  {
    id: '2',
    _id: '2',
    storeName: 'Fashion Hub',
    storeSlug: 'fashion-hub',
    name: 'Fashion Hub',
    ownerName: 'Priya Sharma',
    email: 'info@fashionhub.com',
    phone: '+91-9876543220',
    alternatePhone: '+91-9876543221',
    whatsappNumber: '+91-9876543220',
    businessType: 'company' as const,
    gstNumber: '27AAPCT5678H1Z0',
    panNumber: 'AAACT5678H',
    businessRegistrationNumber: 'BRN-2024-002',
    description: 'Latest fashion trends and apparel for men, women, and kids.',
    address1: '456 Fashion Lane',
    address2: 'Suite 200',
    city: 'Mumbai',
    state: 'Maharashtra',
    pinCode: '400001',
    country: 'India',
    bankName: 'ICICI Bank',
    accountHolderName: 'Fashion Hub Pvt Ltd',
    accountNumber: '2345678901234567',
    ifscCode: 'ICIC0002345',
    upiId: 'fashionhub@icici',
    logo: 'https://via.placeholder.com/200x200?text=Fashion+Hub',
    banner: 'https://via.placeholder.com/1920x400?text=Fashion+Hub+Banner',
    commissionRate: 6.0,
    allowedCategories: ['2'],
    products: 45,
    facebook: 'https://facebook.com/fashionhub',
    instagram: 'https://instagram.com/fashionhub',
    twitter: 'https://twitter.com/fashionhub',
    website: 'https://fashionhub.com',
    idProof: 'https://example.com/id-proof-2.pdf',
    addressProof: 'https://example.com/address-proof-2.pdf',
    gstCertificate: 'https://example.com/gst-cert-2.pdf',
    cancelledCheque: 'https://example.com/cheque-2.pdf',
    status: 'approved' as const,
    approvalNotes: 'Approved',
    emailVerified: true,
    phoneVerified: true,
    documentsVerified: true,
    username: 'fashion_hub',
    password: 'hashed_password_here',
    sendCredentialsEmail: false,
    registrationDate: '2024-02-20',
  },
  {
    id: '3',
    _id: '3',
    storeName: 'Green Living',
    storeSlug: 'green-living',
    name: 'Green Living Store',
    ownerName: 'Arjun Singh',
    email: 'hello@greenliving.com',
    phone: '+91-9876543230',
    alternatePhone: '+91-9876543231',
    whatsappNumber: '+91-9876543230',
    businessType: 'individual' as const,
    gstNumber: '',
    panNumber: 'AAACT9101H',
    businessRegistrationNumber: '',
    description: 'Eco-friendly sustainable products for a green lifestyle.',
    address1: '789 Eco Park',
    address2: '',
    city: 'Delhi',
    state: 'Delhi',
    pinCode: '110001',
    country: 'India',
    bankName: 'Axis Bank',
    accountHolderName: 'Arjun Singh',
    accountNumber: '3456789012345678',
    ifscCode: 'AXIS0003456',
    upiId: 'greenliving@axis',
    logo: 'https://via.placeholder.com/200x200?text=Green+Living',
    banner: 'https://via.placeholder.com/1920x400?text=Green+Living+Banner',
    commissionRate: 7.0,
    allowedCategories: ['3'],
    products: 12,
    facebook: 'https://facebook.com/greenliving',
    instagram: 'https://instagram.com/greenliving',
    twitter: '',
    website: 'https://greenliving.com',
    idProof: 'https://example.com/id-proof-3.pdf',
    addressProof: 'https://example.com/address-proof-3.pdf',
    gstCertificate: '',
    cancelledCheque: 'https://example.com/cheque-3.pdf',
    status: 'pending' as const,
    approvalNotes: 'Under review. Pending GST verification.',
    emailVerified: true,
    phoneVerified: false,
    documentsVerified: false,
    username: 'green_living',
    password: 'hashed_password_here',
    sendCredentialsEmail: true,
    registrationDate: '2024-11-10',
  },
  {
    id: '4',
    _id: '4',
    storeName: 'Home Essentials',
    storeSlug: 'home-essentials',
    name: 'Home Essentials',
    ownerName: 'Neha Patel',
    email: 'support@homeessentials.com',
    phone: '+91-9876543240',
    alternatePhone: '+91-9876543241',
    whatsappNumber: '+91-9876543240',
    businessType: 'company' as const,
    gstNumber: '27AAPCT2109H1Z0',
    panNumber: 'AAACT2109H',
    businessRegistrationNumber: 'BRN-2024-004',
    description: 'Quality home and kitchen products for modern living.',
    address1: '321 Home Plaza',
    address2: 'Floor 3',
    city: 'Pune',
    state: 'Maharashtra',
    pinCode: '411001',
    country: 'India',
    bankName: 'SBI',
    accountHolderName: 'Home Essentials Ltd',
    accountNumber: '4567890123456789',
    ifscCode: 'SBIN0004567',
    upiId: 'homeessentials@sbi',
    logo: 'https://via.placeholder.com/200x200?text=Home+Essentials',
    banner: 'https://via.placeholder.com/1920x400?text=Home+Essentials+Banner',
    commissionRate: 5.0,
    allowedCategories: ['3', '5'],
    products: 67,
    facebook: 'https://facebook.com/homeessentials',
    instagram: 'https://instagram.com/homeessentials',
    twitter: 'https://twitter.com/homeessentials',
    website: 'https://homeessentials.com',
    idProof: 'https://example.com/id-proof-4.pdf',
    addressProof: 'https://example.com/address-proof-4.pdf',
    gstCertificate: 'https://example.com/gst-cert-4.pdf',
    cancelledCheque: 'https://example.com/cheque-4.pdf',
    status: 'approved' as const,
    approvalNotes: 'Fully verified and approved',
    emailVerified: true,
    phoneVerified: true,
    documentsVerified: true,
    username: 'home_essentials',
    password: 'hashed_password_here',
    sendCredentialsEmail: false,
    registrationDate: '2024-03-05',
  },
  {
    id: '5',
    _id: '5',
    storeName: 'Books World',
    storeSlug: 'books-world',
    name: 'Books World',
    ownerName: 'Vikram Malhotra',
    email: 'info@booksworld.com',
    phone: '+91-9876543250',
    alternatePhone: '+91-9876543251',
    whatsappNumber: '+91-9876543250',
    businessType: 'company' as const,
    gstNumber: '27AAPCT3344H1Z0',
    panNumber: 'AAACT3344H',
    businessRegistrationNumber: 'BRN-2024-005',
    description: 'Vast collection of books and publications from around the world.',
    address1: '654 Library Street',
    address2: 'Main Branch',
    city: 'Kolkata',
    state: 'West Bengal',
    pinCode: '700001',
    country: 'India',
    bankName: 'Bank of India',
    accountHolderName: 'Books World Pvt Ltd',
    accountNumber: '5678901234567890',
    ifscCode: 'BKID0005678',
    upiId: 'booksworld@bkid',
    logo: 'https://via.placeholder.com/200x200?text=Books+World',
    banner: 'https://via.placeholder.com/1920x400?text=Books+World+Banner',
    commissionRate: 8.0,
    allowedCategories: ['5'],
    products: 156,
    facebook: 'https://facebook.com/booksworld',
    instagram: 'https://instagram.com/booksworld',
    twitter: 'https://twitter.com/booksworld',
    website: 'https://booksworld.com',
    idProof: 'https://example.com/id-proof-5.pdf',
    addressProof: 'https://example.com/address-proof-5.pdf',
    gstCertificate: 'https://example.com/gst-cert-5.pdf',
    cancelledCheque: 'https://example.com/cheque-5.pdf',
    status: 'approved' as const,
    approvalNotes: 'High-quality seller with excellent ratings',
    emailVerified: true,
    phoneVerified: true,
    documentsVerified: true,
    username: 'books_world',
    password: 'hashed_password_here',
    sendCredentialsEmail: false,
    registrationDate: '2024-01-10',
  },
  {
    id: '6',
    _id: '6',
    storeName: 'Sports Pro',
    storeSlug: 'sports-pro',
    name: 'Sports Pro',
    ownerName: 'Aditya Gupta',
    email: 'contact@sportspro.com',
    phone: '+91-9876543260',
    alternatePhone: '+91-9876543261',
    whatsappNumber: '+91-9876543260',
    businessType: 'company' as const,
    gstNumber: '27AAPCT5566H1Z0',
    panNumber: 'AAACT5566H',
    businessRegistrationNumber: 'BRN-2024-006',
    description: 'Professional sports equipment and gear for athletes and enthusiasts.',
    address1: '987 Sports Complex',
    address2: 'Tower B',
    city: 'Hyderabad',
    state: 'Telangana',
    pinCode: '500001',
    country: 'India',
    bankName: 'Yes Bank',
    accountHolderName: 'Sports Pro Enterprises',
    accountNumber: '6789012345678901',
    ifscCode: 'YESB0006789',
    upiId: 'sportspro@yesb',
    logo: 'https://via.placeholder.com/200x200?text=Sports+Pro',
    banner: 'https://via.placeholder.com/1920x400?text=Sports+Pro+Banner',
    commissionRate: 6.5,
    allowedCategories: ['4'],
    products: 34,
    facebook: 'https://facebook.com/sportspro',
    instagram: 'https://instagram.com/sportspro',
    twitter: 'https://twitter.com/sportspro',
    website: 'https://sportspro.com',
    idProof: 'https://example.com/id-proof-6.pdf',
    addressProof: 'https://example.com/address-proof-6.pdf',
    gstCertificate: 'https://example.com/gst-cert-6.pdf',
    cancelledCheque: 'https://example.com/cheque-6.pdf',
    status: 'pending' as const,
    approvalNotes: 'Awaiting final document verification',
    emailVerified: true,
    phoneVerified: true,
    documentsVerified: false,
    username: 'sports_pro',
    password: 'hashed_password_here',
    sendCredentialsEmail: true,
    registrationDate: '2024-11-12',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Wireless Headphones',
    category: 'Electronics',
    vendor: 'TechGear Co',
    price: 79.99,
    stock: 145,
    status: 'active' as const,
    image: '/wireless-headphones.png',
    images: ['/wireless-headphones.png'],
    seoStatus: 'complete' as const,
    metaTitle: 'Premium Wireless Headphones',
    metaDescription: 'High-quality wireless headphones with noise cancellation',
  },
  {
    id: '2',
    name: 'Running Shoes',
    category: 'Sports',
    vendor: 'Sports Pro',
    price: 129.99,
    stock: 89,
    status: 'active' as const,
    image: '/running-shoes.jpg',
    images: ['/running-shoes.jpg'],
    seoStatus: 'partial' as const,
    metaTitle: 'Running Shoes',
    metaDescription: '',
  },
  {
    id: '3',
    name: 'Summer Dress',
    category: 'Fashion',
    vendor: 'Fashion Hub',
    price: 59.99,
    stock: 0,
    status: 'inactive' as const,
    image: '/woman-in-floral-summer-dress.png',
    images: ['/woman-in-floral-summer-dress.png'],
    seoStatus: 'missing' as const,
    metaTitle: '',
    metaDescription: '',
  },
  {
    id: '4',
    name: 'Bamboo Cutting Board',
    category: 'Home & Kitchen',
    vendor: 'Home Essentials',
    price: 24.99,
    stock: 234,
    status: 'active' as const,
    image: '/bamboo-cutting-board.png',
    images: ['/bamboo-cutting-board.png'],
    seoStatus: 'complete' as const,
    metaTitle: 'Organic Bamboo Cutting Board',
    metaDescription: 'Eco-friendly bamboo cutting board for your kitchen',
  },
  {
    id: '5',
    name: 'JavaScript Guide',
    category: 'Books',
    vendor: 'Books World',
    price: 39.99,
    stock: 567,
    status: 'active' as const,
    image: '/javascript-book.png',
    images: ['/javascript-book.png'],
    seoStatus: 'complete' as const,
    metaTitle: 'Complete JavaScript Guide',
    metaDescription: 'Master JavaScript programming from basics to advanced',
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1-555-0201',
    orders: 12,
    spent: 1245.50,
    registrationDate: '2024-01-20',
    status: 'active' as const,
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1-555-0202',
    orders: 5,
    spent: 342.75,
    registrationDate: '2024-03-15',
    status: 'active' as const,
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    phone: '+1-555-0203',
    orders: 23,
    spent: 3456.20,
    registrationDate: '2024-02-10',
    status: 'active' as const,
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    phone: '+1-555-0204',
    orders: 0,
    spent: 0,
    registrationDate: '2024-11-01',
    status: 'blocked' as const,
  },
];

export const MOCK_CATEGORIES = [
  { id: '1', name: 'Electronics', slug: 'electronics', seoStatus: 'complete' as const, products: 145 },
  { id: '2', name: 'Fashion', slug: 'fashion', seoStatus: 'partial' as const, products: 287 },
  { id: '3', name: 'Home & Kitchen', slug: 'home-kitchen', seoStatus: 'complete' as const, products: 456 },
  { id: '4', name: 'Sports', slug: 'sports', seoStatus: 'missing' as const, products: 89 },
  { id: '5', name: 'Books', slug: 'books', seoStatus: 'complete' as const, products: 678 },
];

export const MOCK_DASHBOARD = {
  stats: {
    vendors: { total: 6, pending: 2 },
    customers: { total: 4, active: 3 },
    products: { total: 5, active: 4 },
    categories: { total: 5 },
    seoScore: 84,
  },
  salesData: [
    { date: 'Mon', sales: 4200 },
    { date: 'Tue', sales: 5100 },
    { date: 'Wed', sales: 3800 },
    { date: 'Thu', sales: 4900 },
    { date: 'Fri', sales: 6200 },
    { date: 'Sat', sales: 5800 },
    { date: 'Sun', sales: 4100 },
  ],
  topVendors: [
    { name: 'Books World', products: 156, sales: 8900 },
    { name: 'Home Essentials', products: 67, sales: 7200 },
    { name: 'Fashion Hub', products: 45, sales: 6100 },
    { name: 'TechGear Co', products: 24, sales: 5200 },
    { name: 'Sports Pro', products: 34, sales: 4800 },
  ],
  topCustomers: [
    { name: 'Mike Johnson', orders: 23, spent: 3456.20 },
    { name: 'John Doe', orders: 12, spent: 1245.50 },
    { name: 'Jane Smith', orders: 5, spent: 342.75 },
  ],
  recentActivity: [
    { id: '1', action: 'New vendor registered', details: 'Green Living Store', timestamp: '2 hours ago' },
    { id: '2', action: 'Product added', details: 'Wireless Headphones by TechGear Co', timestamp: '4 hours ago' },
    { id: '3', action: 'Customer registered', details: 'John Doe', timestamp: '1 day ago' },
    { id: '4', action: 'Vendor approved', details: 'Fashion Hub', timestamp: '2 days ago' },
    { id: '5', action: 'Product updated', details: 'Running Shoes SEO optimized', timestamp: '3 days ago' },
  ],
  seoHealth: {
    productsWithoutMeta: 2,
    categoriesWithoutMeta: 1,
    pagesWithoutAlt: 3,
    duplicateMetas: 0,
    overallScore: 84,
  },
};
